Repository byzer-org/byzer-lang, pull requests merged in 2018-11, with the labels that each got.

#674 Update mlsql-stream.md
  docs/en/mlsql-stream.md
  docs/mlsql-stream.md
Labels: Documentation Plan, MSQL-1.1.5

#681 [DEV][update] update version to 1.1.5-SNAPSHOT
  pom.xml
  streamingpro-api/pom.xml
  streamingpro-assembly/pom.xml
  streamingpro-automl/pom.xml
  streamingpro-commons/pom.xml
  streamingpro-crawler/pom.xml
  streamingpro-dl4j/pom.xml
  streamingpro-dsl-legacy/pom.xml
  streamingpro-dsl/pom.xml
  streamingpro-flink/pom.xml
  streamingpro-hbase/pom.xml
  streamingpro-jython/pom.xml
  streamingpro-manager/pom.xml
  streamingpro-mlsql/pom.xml
  streamingpro-opencv/pom.xml
  streamingpro-redis/pom.xml
  streamingpro-spark-2.2.0-adaptor/pom.xml
  streamingpro-spark-2.3.0-adaptor/pom.xml
  streamingpro-spark-2.4.0-adaptor/pom.xml
  streamingpro-spark-common/pom.xml
  streamingpro-spark/pom.xml
  streamingpro-tensorflow/pom.xml
  streamingpro-xgboost/pom.xml
Labels: MSQL-1.1.5

#698 [Dev]Fix all unit tests
  streamingpro-mlsql/src/main/java/streaming/dsl/ScriptSQLExec.scala
  streamingpro-mlsql/src/main/java/streaming/dsl/load/batch/AutoWorkflowExplain.scala
  streamingpro-mlsql/src/main/resources-local/test/sql/feature-extract.sql
  streamingpro-mlsql/src/main/resources-local/test/sql/model-explain.sql
  streamingpro-mlsql/src/main/resources-online/test/batch-mlsql-error.json
  streamingpro-mlsql/src/main/resources-online/test/sql/feature-extract.sql
  streamingpro-mlsql/src/main/resources-online/test/sql/python-alg-script-enable-data-local.sql
  streamingpro-mlsql/src/main/resources-online/test/sql/python-alg-script.sql
  streamingpro-mlsql/src/test/scala/streaming/core/SpecFunctions.scala
  streamingpro-mlsql/src/test/scala/streaming/test/dsl/DslSpec.scala
  streamingpro-mlsql/src/test/scala/streaming/test/mysql/MySQLSpec.scala
  streamingpro-mlsql/src/test/scala/streaming/test/processing/TextSpec.scala
  streamingpro-spark-2.2.0-adaptor/src/main/java/org/apache/spark/MLSQLSyntaxErrorListener.scala
  streamingpro-spark-2.3.0-adaptor/src/main/java/org/apache/spark/MLSQLSyntaxErrorListener.java
  streamingpro-spark-2.4.0-adaptor/src/main/java/org/apache/spark/MLSQLSyntaxErrorListener.java
Labels: Improvement, MSQL-1.1.5

#687 modify session clearing policy
  streamingpro-mlsql/src/main/java/streaming/session/SessionManager.scala
  streamingpro-mlsql/src/test/scala/streaming/core/BasicMLSQLConfig.scala
  streamingpro-mlsql/src/test/scala/streaming/test/session/SessionSpec.scala
Labels: Improvement, MSQL-1.1.5

#708 remove streamingpro-tensorflow from pom
  streamingpro-mlsql/pom.xml
  streamingpro-spark-2.2.0-adaptor/pom.xml
  streamingpro-spark-2.3.0-adaptor/pom.xml
  streamingpro-spark-2.4.0-adaptor/pom.xml
Labels: Fixed, MSQL-1.1.5, bug

#678 [CORE][fix] new session will inherit Root SparkSession in sessionPerUser mode
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/MLSQLException.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/MLSQLOperation.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/MLSQLOperationManager.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/MLSQLSession.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/MLSQLSparkSession.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/OpIdentifier.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/ReflectUtils.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/SessionIdentifier.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/SessionManager.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/SparkSessionCacheManager.scala
  streamingpro-mlsql/src/main/java/org/apache/spark/sql/mlsql/session/operation/OperationState.scala
  streamingpro-mlsql/src/main/java/streaming/core/strategy/platform/SparkRuntime.scala
  streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLCacheExt.scala
  streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLImageLoaderExt.scala
  streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/SQLMnistLoaderExt.scala
  streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/bigdl/BigDLClassifyExtParamsExtractor.scala
  streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/python/Project.scala
  streamingpro-mlsql/src/main/java/streaming/session/SessionIdentifier.scala
  streamingpro-mlsql/src/test/scala/org/apache/spark/streaming/BasicSparkOperation.scala
  streamingpro-mlsql/src/test/scala/streaming/test/session/SessionSpec.scala
Labels: MSQL-1.1.5, bug

#672 [ScriptUDF][update] refatoring ScriptUDF module
  streamingpro-commons/src/main/java/streaming/common/SourceCodeCompiler.scala
  streamingpro-jython/src/main/java/streaming/jython/PythonInterp.java
  streamingpro-mlsql/src/main/java/streaming/dsl/mmlib/algs/ScriptUDF.scala
  streamingpro-mlsql/src/main/java/streaming/parser/SparkTypePaser.scala
  streamingpro-mlsql/src/main/java/streaming/udf/PythonRuntimeCompileUDAF.scala
  streamingpro-mlsql/src/main/java/streaming/udf/PythonRuntimeCompileUDF.scala
  streamingpro-mlsql/src/main/java/streaming/udf/PythonSourceUDF.scala
  streamingpro-mlsql/src/main/java/streaming/udf/RuntimeCompileScriptInterface.scala
  streamingpro-mlsql/src/main/java/streaming/udf/RuntimeCompileUDAF.scala
  streamingpro-mlsql/src/main/java/streaming/udf/RuntimeCompileUDF.scala
  streamingpro-mlsql/src/main/java/streaming/udf/ScalaRuntimeCompileUDAF.scala
  streamingpro-mlsql/src/main/java/streaming/udf/ScalaRuntimeCompileUDF.scala
  streamingpro-mlsql/src/test/scala/org/apache/spark/streaming/BasicSparkOperation.scala
  streamingpro-mlsql/src/test/scala/streaming/core/BasicMLSQLConfig.scala
  streamingpro-mlsql/src/test/scala/streaming/dsl/mmlib/algs/ScriptUDFSuite.scala
  streamingpro-mlsql/src/test/scala/streaming/test/dsl/DslSpec.scala
Labels: Feature, MLSQL-1.1.6
